server:
  port: 0
spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
      password: ''
      username: ''